C ======================================================================
C
C     NLPQLG : SUCCESSIVE EXECUTION OF NLPQLP FOR A STEPWISE
C              IMPROVEMENT OF LOCAL MINIMA
C
C     NLPQLG executes the SQP code NLPQLP successively for NCYCLE
C     different starting points and returns the best local solution
C     found.  The first cycle proceeds from the starting point provided
C     by the calling program.  Every further cycle is started from a
C     point of the feasible box which is generated by a deterministic
C     Kronecker sequence
C
C          t_i^(k) = frac( k * sqrt(p_i) ) ,  p_i the i-th odd number,
C
C     i.e., x_i = xl_i + t_i (xu_i - xl_i) for finite bounds and
C     x_i = x_i^* + (2 t_i - 1)(1 + |x_i^*|) otherwise, where x^* is the
C     best solution obtained so far.  The sequence is completely
C     reproducible, no random number generator is involved.
C
C     Function and gradient values are provided by reverse
C     communication exactly as for NLPQLP.  The best feasible solution
C     is returned in X, F and G.
C
C   PARAMETERS:
C
C      All parameters are identical to those of NLPQLP with the
C      exception of
C
C      NCYCLE  : Number of successive executions of NLPQLP, >= 1.
C      LWA     : Length of WA, at least the length required by NLPQLP
C                plus 2*N + M + 12.
C
C ======================================================================
C
      SUBROUTINE NLPQLG (NP, M, ME, MMAX, N, NMAX, MNN2, X, F, G,
     /                   DF, DG, U, XL, XU, C, D, ACC, ACCQP, STPMIN,
     /                   MAXFUN, MAXIT, MAXNM, RHO, NCYCLE, IPRINT,
     /                   MODE, IOUT, IFAIL, WA, LWA, KWA, LKWA, ACT,
     /                   LACT, LQL, QPSLVE)
C
      IMPLICIT NONE
      INTEGER NP, M, ME, MMAX, N, NMAX, MNN2, MAXFUN, MAXIT, MAXNM,
     /        NCYCLE, IPRINT, MODE, IOUT, IFAIL, LWA, LKWA, LACT
      INTEGER KWA(LKWA)
      DOUBLE PRECISION X(NMAX,*), F(*), G(MMAX,*), DF(*), DG(MMAX,*),
     /                 U(*), XL(*), XU(*), C(NMAX,*), D(*), WA(LWA),
     /                 ACC, ACCQP, STPMIN, RHO
      LOGICAL ACT(LACT), LQL
      EXTERNAL QPSLVE
C
      INTEGER MG, LXB, LFB, LGB, LST, LW, LWW
C
      MG  = MAX(M,1)
      LXB = 1
      LFB = LXB + N
      LGB = LFB + 1
      LST = LGB + MG
      LW  = LST + 8
      LWW = LWA - LW + 1
      IF (LWW.LT.1 .OR. NCYCLE.LT.1) THEN
         IFAIL = 5
         RETURN
      ENDIF
      CALL NLPQLGW (NP, M, ME, MMAX, N, NMAX, MNN2, X, F, G, DF, DG,
     /              U, XL, XU, C, D, ACC, ACCQP, STPMIN, MAXFUN,
     /              MAXIT, MAXNM, RHO, NCYCLE, IPRINT, MODE, IOUT,
     /              IFAIL, WA(LXB), WA(LFB), WA(LGB), WA(LST),
     /              WA(LW), LWW, KWA, LKWA, ACT, LACT, LQL, QPSLVE)
      RETURN
      END
